---
# tasks file for vagrant_destroy
- name: vagrant destroy for each os type
  ansible.builtin.shell:
    cmd: vagrant destroy
  loop: 
    - rhel9
    - rhel8
    - centos9s
    - centos8s
    - fedora36


