---
# tasks file for vagrant_destroy
- name: vagrant destroy for each os type
  ansible.builtin.command:
    cmd: vagrant destroy --force
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
  loop: 
    - rhel9
    - rhel8
    - centos9s
    - fedora36

# tasks file for vagrant_cleanup
- name: remove vagrant directories
  ansible.builtin.file:
    dest: "/home/{{ ansible_user_id }}/vagrant"
    state: absent
