---
# tasks file for vagrant_up
- name: vagrant up for each os type
  ansible.builtin.shell:
    cmd: vagrant up
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
  loop: 
    - rhel9
    - rhel8
    - centos9s
    - centos8s
    - fedora36
