---
# tasks file for vagrant_inventory
- name: get ip address and assign to variable to update inventory
  ansible.builtin.shell:
    cmd: vagrant ssh-config | grep HostName | awk '{ print $2 }' 
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
  register: result
  loop: "{{ os_ver }}"

- name: create inventory file
  ansible.builtin.template:
    src: templates/inventory.j2
    dest: /home/{{ ansible_user_id }}/vagrant/inventory.ini

- name: update local ansible file to know where inventory is
  ansible.builtin.template:
    src: templates/ansiblecfg.j2
    dest: "/home/{{ ansible_user_id }}/.ansible.cfg"

- name: symlink ssh config to .ssh/config
  ansible.builtin.file:
    src: "/home/{{ ansible_user_id }}/vagrant/{{ item }}/.vagrant/machines/default/libvirt/private_key"
    dest: "/home/{{ ansible_user_id }}/.ssh/{{ item }}"
    state: link
  loop: "{{ os_ver }}"

- name: add ssh conf for new ssh keys
  ansible.builtin.command:
    cmd: "echo ~/.ssh/{{ item }} >> home/{{ ansible_user_id }}/vagrant/vagrant.conf"
  loop: "{{ os_ver }}"



    