---
# tasks file for vagrant
- name: Install Packages
  ansible.builtin.dnf:
    state: latest
    name:
      - qemu-kvm 
      - libvirt 
      - libguestfs-tools 
      - virt-install 
      - rsync
      - vagrant
      - vagrant-libvirt

- name: vagrant plugin install vagrant-libvirt
  ansible.builtin.command:
    cmd: vagrant plugin install vagrant-libvirt

- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: add ssh conf for new ssh keys
  ansible.builtin.shell:
     cmd: "echo IdentityFile /home/{{ remote_regular_user }}/.ssh/{{ item }} >> /etc/ssh/ssh_config.d/vagrant.conf"
     creates: /etc/ssh/ssh_config.d/vagrant.conf
  loop: "{{ os_ver }}"

- name: ensure libvirtd network service is enabled
  ansible.builtin.service:
    name: virtnetworkd
    enabled: true

- name: ensure libvirtd network service is running
  ansible.builtin.service:
    name: virtnetworkd
    state: running