---
# tasks file for vagrant_config
- name: Create Vagrant directory
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0775 
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  loop:
    - "/home/{{ ansible_user_id }}/vagrant"
    - "/home/{{ ansible_user_id }}/vagrant/rhel9"

- name: init vagrant box for each os type
  ansible.builtin.command:
    cmd: "vagrant box add generic/{{ item }} --provider=libvirt --force"
  loop: "{{ os_ver }}"

- name: init vagrant for each os type
  ansible.builtin.command:
    cmd: "vagrant init generic/{{ item }}"
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
    creates: Vagrantfile
  loop: "{{ os_ver }}"
