---
# tasks file for vagrant_down
- name: vagrant halt for each os type
  ansible.builtin.command:
    cmd: vagrant halt
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
  register: up_info
  loop: "{{ os_ver }}"
