---
# tasks file for vagrant_cleanup

- name: remove vagrant directories
  ansible.builtin.file:
    dest: "/home/{{ ansible_user_id }}/vagrant"
    state: absent

- name: virsh destroy domains/vms
  ansible.builtin.command:
    cmd: "virsh destroy {{ item }}_default"
  loop: "{{ os_ver }}"

- name: virsh undefine domains/vms
  ansible.builtin.command:
    cmd: "virsh undefine {{ item }}_default --remove-all-storage"
  loop: "{{ os_ver }}"

