---
# tasks file for vagrant_destroy
- name: vagrant up for each os type
  ansible.builtin.shell:
    cmd: vagrant destroy
    chdir: "/home/{{ ansible_user_id }}/vagrant/{{ item }}"
    creates: Vagrantfile
  register: up_info
  loop: 
    - rhel9
    - rhel8
    - centos9s
    - centos8s
    - fedora36
